import { Inter } from "next/font/google";
import "../style/globals.css";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Citas",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="w-screen h-screen">
      <body className={inter.className} suppressHydrationWarning={true}>{children}</body>
    </html>
  );
}
