apiVersion: v1
kind: Pod
metadata:
  name: backend-dates-pod
  labels:
    app: dates
    
spec:
  containers:
    - name: backend-dates-container
      image: heroslaver/backend:latest
      ports:
        - containerPort: 8000


---

apiVersion: v1
kind: Service
metadata:
  name: backend-dates-service
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: dates
