apiVersion: v1
kind: Pod
metadata:
  name: frontend-dates-pod
  labels:
    app: dates
    
spec:
  containers:
    - name: frontend-dates-container
      image: heroslaver/frontend-dates:latest
      ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-dates-service
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      nodePort: 31235
  selector:
    app: dates

