# Generated by Django 3.2.8 on 2024-06-08 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dates',
            name='username',
        ),
    ]
