# Generated by Django 3.2.8 on 2024-04-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dates',
            name='pet_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
