# Generated by Django 3.2.8 on 2024-04-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0002_dates_pet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dates',
            name='pet_id',
            field=models.IntegerField(),
        ),
    ]
