# Generated by Django 3.2.8 on 2024-06-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0002_remove_dates_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dates',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='dates',
            name='username',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='dates',
            name='apellido',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dates',
            name='nombre',
            field=models.TextField(),
        ),
    ]
