# Generated by Django 3.2.8 on 2024-06-08 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0003_auto_20240608_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dates',
            old_name='apellido',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='dates',
            old_name='nombre',
            new_name='name',
        ),
    ]
