# Generated by Django 3.2.8 on 2024-05-26 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0004_auto_20240427_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dates',
            name='date_time',
            field=models.DateField(),
        ),
    ]
